services:
  web:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
  web-tests:
    image: vidly-web
    volumes:
      - ./frontend:/app
    command: npm test
    environment:
      - CI=true
  api:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      # - DB_URL=mongodb://db/vidly
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app # Bind Mount, changes sync instantly(host:container), no need to rebuild the image!
    # command: ./wait-for db:27017 && migrate-mongo up && npm start
    command: ./docker-entrypoint.sh
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly: # we need to create this volume first